/* Types for products */

export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const FETCH_SINGLE_PRODUCT = "FETCH_SINGLE_PRODUCT";
export const SET_PRODUCTS = "SET_PRODUCTS";
export const ADD_SELECTED_PRODUCT = "SELECTED_PRODUCT";
export const REMOVE_SELECTED_PRODUCT = "REMOVE_SELECTED_PRODUCT";
